### ISSUE TITLE
Cannot find file `components/article-lists/title-preview-author-media-flipped/tmp-8568VkrbJw1yMGfO/screenshot.jpg` during build. 

### ISSUE THREAD

**Issue by levibostian** [tachyons-css/tachyons-css.github.io#146]
During `npm start`, I am receiving this issue:

```
> tachyons-css.github.io@4.6.1 start /Users/levibostian/code/tachyons-css.github.io
> npm run css && node build.js


> tachyons-css.github.io@4.6.1 css /Users/levibostian/code/tachyons-css.github.io
> tachyons src/css/tachyons.css > css/tachyons.css && tachyons src/css/tachyons.css --minify > css/tachyons.min.css

Working on components list...
- Created components list (JSON): tmp/components.json
Done with components list! 9.56 s
Working on components index...
- Created index "Components": components/index.html
- Created index "Recent Components": components/recent.html
Done with components index! 56 ms
Working on components RSS feed...
- Created RSS feed: components/rss.xml
Done with components RSS feed! 9.68 ms
Working on components pages...
  * Created page for: src/components/article-lists/title-preview-author-media-flipped.html
  * Created page for: src/components/article-lists/title-preview-author-media.html
  * Created page for: src/components/articles/feature.html
  * Created page for: src/components/articles/full-bleed-background.html
  * Created page for: src/components/articles/headline-title-text.html
  * Created page for: src/components/articles/large-title-text.html
  * Created page for: src/components/articles/left-title-top-border.html
  * Created page for: src/components/articles/left-title.html
  * Created page for: src/components/articles/photo-essay.html
  * Created page for: src/components/articles/single-column-large-title.html
  * Created page for: src/components/articles/title-highlight-header-cover.html
  * Created page for: src/components/articles/title-text-image.html
  * Created page for: src/components/articles/title-text.html
  * Created page for: src/components/avatars/circle-border.html
  * Created page for: src/components/avatars/circle.html
  * Created page for: src/components/avatars/double-ring.html
  * Created page for: src/components/avatars/rounded-large.html
  * Created page for: src/components/avatars/rounded-medium.html
  * Created page for: src/components/avatars/rounded-small.html
  * Created page for: src/components/avatars/square.html
  * Created page for: src/components/banners/basic.html
  * Created page for: src/components/banners/info.html
  * Created page for: src/components/banners/single-cta.html
  * Created page for: src/components/buttons/basic-previous-next.html
  * Created page for: src/components/buttons/basic-rounded-extra-small.html
  * Created page for: src/components/buttons/basic-rounded-small.html
  * Created page for: src/components/buttons/basic-rounded.html
  * Created page for: src/components/buttons/basic.html
  * Created page for: src/components/buttons/centered-icons.html
  * Created page for: src/components/buttons/pill-grow.html
  * Created page for: src/components/buttons/pill.html
  * Created page for: src/components/cards/album-centered.html
  * Created page for: src/components/cards/album-left.html
  * Created page for: src/components/cards/basic-text-card.html
  * Created page for: src/components/cards/news-card.html
  * Created page for: src/components/cards/product-card.html
  * Created page for: src/components/cards/profile-card-title-subtitle.html
  * Created page for: src/components/cards/profile-card.html
  * Created page for: src/components/cards/suggested-profile.html
  * Created page for: src/components/cards/text-card.html
  * Created page for: src/components/collections/albums.html
  * Created page for: src/components/collections/movies.html
  * Created page for: src/components/collections/posters-dim.html
  * Created page for: src/components/collections/posters.html
  * Created page for: src/components/collections/square-title-subtitle.html
  * Created page for: src/components/collections/vinyl.html
  * Created page for: src/components/definition-lists/inline.html
  * Created page for: src/components/definition-lists/simple.html
  * Created page for: src/components/error-pages/404.html
  * Created page for: src/components/footers/centered-icons-hover-glow.html
  * Created page for: src/components/footers/inline-text.html
  * Created page for: src/components/footers/simple-large-type.html
  * Created page for: src/components/footers/small-print.html
  * Created page for: src/components/footers/social-circles.html
  * Created page for: src/components/footers/social-simple-text.html
  * Created page for: src/components/footers/social-simple.html
  * Created page for: src/components/footers/social-text.html
  * Created page for: src/components/footers/social.html
  * Created page for: src/components/footers/studios.html
  * Created page for: src/components/forms/checkbox-list.html
  * Created page for: src/components/forms/input-text-label.html
  * Created page for: src/components/forms/newsletter-subscription.html
  * Created page for: src/components/forms/password.html
  * Created page for: src/components/forms/sign-in.html
  * Created page for: src/components/forms/sign-up.html
  * Created page for: src/components/forms/textarea-label.html
  * Created page for: src/components/headers/circle-avatar-title-subtitle.html
  * Created page for: src/components/headers/rounded-avatar-title-subtitle.html
  * Created page for: src/components/headers/startup-hero.html
  * Created page for: src/components/layout/aspect-ratio-16x9.html
  * Created page for: src/components/layout/aspect-ratio-1x1.html
  * Created page for: src/components/layout/aspect-ratio-3x4.html
  * Created page for: src/components/layout/aspect-ratio-4x3.html
  * Created page for: src/components/layout/aspect-ratio-4x6.html
  * Created page for: src/components/layout/aspect-ratio-5x7.html
  * Created page for: src/components/layout/aspect-ratio-5x8.html
  * Created page for: src/components/layout/aspect-ratio-6x4.html
  * Created page for: src/components/layout/aspect-ratio-7x5.html
  * Created page for: src/components/layout/aspect-ratio-8x5.html
  * Created page for: src/components/layout/aspect-ratio-9x16.html
  * Created page for: src/components/layout/centered-container.html
  * Created page for: src/components/layout/five-column-collapse-alternate.html
  * Created page for: src/components/layout/five-column-collapse-asymmetrical.html
  * Created page for: src/components/layout/five-column-collapse-mixed.html
  * Created page for: src/components/layout/five-column-collapse-one.html
  * Created page for: src/components/layout/five-column.html
  * Created page for: src/components/layout/fixed-table-layout-grid-mixed-rows.html
  * Created page for: src/components/layout/fixed-table-layout-grid.html
  * Created page for: src/components/layout/flag-object-bottom.html
  * Created page for: src/components/layout/flag-object-collapse.html
  * Created page for: src/components/layout/flag-object-top.html
  * Created page for: src/components/layout/flag-object.html
  * Created page for: src/components/layout/four-column-collapse-two-collapse-one.html
  * Created page for: src/components/layout/four-column-collapse-two.html
  * Created page for: src/components/layout/four-column.html
  * Created page for: src/components/layout/full-bleed-16x9.html
  * Created page for: src/components/layout/full-bleed-4x6.html
  * Created page for: src/components/layout/full-bleed-5x7.html
  * Created page for: src/components/layout/full-bleed-5x8.html
  * Created page for: src/components/layout/full-bleed-6x4.html
  * Created page for: src/components/layout/full-bleed-7x5.html
  * Created page for: src/components/layout/full-bleed-8x5.html
  * Created page for: src/components/layout/full-bleed-9x16.html
  * Created page for: src/components/layout/full-bleed-square.html
  * Created page for: src/components/layout/full-screen-centered-title.html
  * Created page for: src/components/layout/horizontal-aspect-ratios.html
  * Created page for: src/components/layout/three-column-collapse-one.html
  * Created page for: src/components/layout/three-column.html
  * Created page for: src/components/layout/two-column-collapse-one.html
  * Created page for: src/components/layout/two-column.html
  * Created page for: src/components/links/animate-background-color.html
  * Created page for: src/components/links/animate-color.html
  * Created page for: src/components/links/dim-no-underline.html
  * Created page for: src/components/links/underline-on-hover.html
  * Created page for: src/components/lists/block-item-dotted-border.html
  * Created page for: src/components/lists/border-spaced.html
  * Created page for: src/components/lists/border-tight.html
  * Created page for: src/components/lists/contact-phone.html
  * Created page for: src/components/lists/follower-notifications-rounded-square-avatar.html
  * Created page for: src/components/lists/follower-notifications.html
  * Created page for: src/components/lists/hashtags.html
  * Created page for: src/components/lists/items-image-title-price.html
  * Created page for: src/components/lists/large-links-inline.html
  * Created page for: src/components/lists/links-animate-color.html
  * Created page for: src/components/lists/links-inline.html
  * Created page for: src/components/lists/links-with-borders-inline.html
  * Created page for: src/components/lists/slab-stat-large.html
  * Created page for: src/components/lists/slab-stat-small.html
  * Created page for: src/components/lists/slab-stat.html
  * Created page for: src/components/lists/title-text.html
  * Created page for: src/components/marketing/iphone-app.html
  * Created page for: src/components/nav/fixed-semi-transparent.html
  * Created page for: src/components/nav/large-title-link-list.html
  * Created page for: src/components/nav/list-overflow.html
  * Created page for: src/components/nav/logo-links-inline-collapse.html
  * Created page for: src/components/nav/logo-links-inline.html
  * Created page for: src/components/nav/logo-titles-links-centered.html
  * Created page for: src/components/nav/minimal-sign-up.html
  * Created page for: src/components/nav/title-link-list.html
  * Created page for: src/components/pages/4x4-mixed-grid.html
  * Created page for: src/components/pages/double.html
  * Created page for: src/components/pages/portfolio-project.html
  * Created page for: src/components/pages/swiss-cover-five-columns.html
  * Created page for: src/components/quotes/left-border.html
  * Created page for: src/components/quotes/pull-quote.html
  * Created page for: src/components/tables/basic.html
  * Created page for: src/components/tables/striped-dark.html
  * Created page for: src/components/text/large-paragraph.html
  * Created page for: src/components/text/narrow-paragraph.html
  * Created page for: src/components/text/paragraph.html
  * Created page for: src/components/text/small-narrow-paragraph.html
  * Created page for: src/components/text/small-paragraph.html
  * Created page for: src/components/text/title-subtitle-centered.html
  * Created page for: src/components/text/wide-paragraph.html
Done with components pages! 8.38 min
Working on components screenshots...
- Started static HTML server on port: 3333
{ Error: Error in file: components/article-lists/title-preview-author-media-flipped/tmp-8568VkrbJw1yMGfO/screenshot.jpg

spawn /Users/levibostian/code/tachyons-css.github.io/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /Users/levibostian/code/tachyons-css.github.io/node_modules/mozjpeg/vendor/cjpeg',
  path: '/Users/levibostian/code/tachyons-css.github.io/node_modules/mozjpeg/vendor/cjpeg',
  spawnargs:
   [ '-outfile',
     '/var/folders/j7/60bqb6hj32q02ny42w9n47cm0000gn/T/40587353-b395-41fd-89a9-1b5a51e08250',
     '-quality',
     90,
     '/var/folders/j7/60bqb6hj32q02ny42w9n47cm0000gn/T/9ede05de-2897-4ebd-98ce-310695ca64bc' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: '/Users/levibostian/code/tachyons-css.github.io/node_modules/mozjpeg/vendor/cjpeg -outfile /var/folders/j7/60bqb6hj32q02ny42w9n47cm0000gn/T/40587353-b395-41fd-89a9-1b5a51e08250 -quality 90 /var/folders/j7/60bqb6hj32q02ny42w9n47cm0000gn/T/9ede05de-2897-4ebd-98ce-310695ca64bc',
  timedOut: false }
```

**Comment by sebastienbarre** [comment]
Which platform / OS?

**Comment by sebastienbarre** [comment]
Unfortunately I can not reproduce your issue (on OSX):
```
Working on components list...
- Created components list (JSON): tmp/components.json
Done with components list! 6.14 s
Working on components index...
- Created index "Components": components/index.html
- Created index "Recent Components": components/recent.html
Done with components index! 36 ms
Working on components RSS feed...
- Created RSS feed: components/rss.xml
Done with components RSS feed! 6.2 ms
Working on components pages...
  * Created page for: src/components/article-lists/title-preview-author-media-flipped.html
  * Created page for: src/components/article-lists/title-preview-author-media.html
  * Created page for: src/components/articles/feature.html
[...]
  * Created page for: src/components/text/title-subtitle-centered.html
  * Created page for: src/components/text/wide-paragraph.html
Done with components pages! 3.4 min
Working on components screenshots...
- Started static HTML server on port: 3333
  * Created screenshot: components/article-lists/title-preview-author-media-flipped/screenshot.jpg (301 KB => 32.31 KB)
  * Created screenshot: components/article-lists/title-preview-author-media/screenshot.jpg (344.85 KB => 38.93 KB)
  * Created screenshot: components/articles/feature/screenshot.jpg (445.94 KB => 14.54 KB)
[...]
  * Created screenshot: components/text/title-subtitle-centered/screenshot.jpg (11.29 KB => 4.88 KB)
  * Created screenshot: components/text/wide-paragraph/screenshot.jpg (19.46 KB => 9.75 KB)
- Closed static HTML server
Done with components screenshots! (22.09 MB => 1.8 MB) 2.8 min
All done 6.33 min
```

**Comment by levibostian** [comment]
I am on macOS. 

I am trying to `rm -rf node_modules/` and `npm install` again to give that a shot. Having more issues: 

```
> tachyons-css.github.io@4.6.1 start /Users/levibostian/code/tachyons-css.github.io
> npm run css && node build.js


> tachyons-css.github.io@4.6.1 css /Users/levibostian/code/tachyons-css.github.io
> tachyons src/css/tachyons.css > css/tachyons.css && tachyons src/css/tachyons.css --minify > css/tachyons.min.css

TypeError: c.hslaString is not a function
    at exports.default (/Users/levibostian/code/tachyons-css.github.io/node_modules/colormin/dist/index.js:59:26)
    at /Users/levibostian/code/tachyons-css.github.io/node_modules/postcss-colormin/dist/index.js:53:53
    at /Users/levibostian/code/tachyons-css.github.io/node_modules/postcss-colormin/dist/index.js:29:22
    at Array.forEach (native)
    at walk (/Users/levibostian/code/tachyons-css.github.io/node_modules/postcss-colormin/dist/index.js:28:18)
    at transform (/Users/levibostian/code/tachyons-css.github.io/node_modules/postcss-colormin/dist/index.js:48:5)
    at /Users/levibostian/code/tachyons-css.github.io/node_modules/postcss-colormin/dist/index.js:74:20
    at /Users/levibostian/code/tachyons-css.github.io/node_modules/postcss/lib/container.js:192:28
    at /Users/levibostian/code/tachyons-css.github.io/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/Users/levibostian/code/tachyons-css.github.io/node_modules/postcss/lib/container.js:114:22)
```

I had this issue yesterday as well. I fixed it by `rm -rf node_modules/` and `npm install`. Done that 3 times just now and still happening.

**Comment by sebastienbarre** [comment]
I would say something is wrong with your toolchain at this point. Or a very old Node.js version. What's your node version?

**Comment by levibostian** [comment]
v6.9.1

**Comment by levibostian** [comment]
Going to close. This seemed to be an issue with my dev environment and I don't care to fix it at the moment anyway 😄. Thanks for the help and patience with *my* issue with my machine.
